Tetris and Snake Leaderboards
PossiblyBobby/4350_002_Fall23_BucStop pull request #29
Opened 2024-03-30 02:15 UTC by DanTuckerCSCI

Got the Tetris and Snake Leader boards started. They currently refer to the same leader board for both games but they are started in the right direction.

2024-04-01 17:17 UTC, jboudou007 requested changes
Code Review Summary: 

**1. Leaderboard Logic and Data Integrity**

**Validation and Security:**  Validated and securely handled leaderboard data from localStorage, ensuring data integrity and a good user experience.

**User Input for Leaderboard:** Introduced a retry mechanism for user initials input by allowing valid data while maintaining fairness and integrity in the leaderboard.

**2. Start Button Functionality and Game State Management**

**Button Positioning and Visibility:** Adjusted the Start button's position for better visibility and ensuring it reappears after the game ends. Also made sure the logic for drawing and handling clicks on the Start button accounts for the game's state, preventing it from disappearing inappropriately or failing to register clicks.

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +let leaderboard = JSON.parse(localStorage.getItem('snakeLeaderboard')) || [];
Same here. Since localStorage is easily accessible through the browser's Developer Tools, it's prone to manual modification by users which could lead to corrupted or unexpected data.

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +let leaderboard = JSON.parse(localStorage.getItem('snakeLeaderboard')) || [];
```suggestion
// Leaderboard logic
// Since localStorage is easily accessible through the browser's Developer Tools, it's prone to manual modification by users.
//This could lead to corrupted or unexpected data.
let leaderboard = [];
try {
  const storedData = JSON.parse(localStorage.getItem("snakeLeaderboard"));
  if (
    Array.isArray(storedData) &&
    storedData.every(
      (entry) =>
        typeof entry.score === "number" &&
        typeof entry.initials === "string" &&
        entry.initials.length <= 3
    )
  ) {
    leaderboard = storedData;
  } else {
    console.warn(
      "Invalid leaderboard data in localStorage, resetting to empty"
    );
  }
} catch (e) {
  console.error("Error parsing leaderboard data:", e);
  // Optionally reset to a default state or handle as needed
}
```

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +}
Input validation by giving the user 3 attempts to enter the initials

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +}
```suggestion
function updateLeaderboard(newScore) {
  let attempts = 3; // Allow the user up to 3 attempts
  let initials = "";

  for (let attempt = 1; attempt <= attempts; attempt++) {
    initials = prompt(
      `Enter your initials (max 3 characters, attempt ${attempt}/${attempts}):`
    ).toUpperCase();
    // Check if the input is valid
    if (initials.match(/^[A-Z]{1,3}$/)) {
      // Valid initials; break out of the loop
      break;
    } else {
      initials = ""; // Reset initials if the input was invalid
      if (attempt < attempts) {
        alert(
          "Invalid initials. Please use up to 3 uppercase letters. A-Z only."
        );
      } else {
        alert("Maximum attempts reached. Your score will not be recorded.");
      }
    }
  }

  // Only add to the leaderboard if initials are valid after the attempts
  if (initials) {
    leaderboard.push({ score: newScore, initials });
    leaderboard.sort((a, b) => b.score - a.score);
    leaderboard = leaderboard.slice(0, maxLeaderboardEntries);
    localStorage.setItem("snakeLeaderboard", JSON.stringify(leaderboard));
  } else {
    // Optionally handle the case where the user fails to enter valid initials
    console.log("Score not recorded due to invalid initials.");
  }
}

```

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +}
Adjusted the position of the leader so it can be centered on the canvas

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +}
```suggestion
// creates the leaderboard
function drawLeaderboard() {
  // Clear the entire canvas to prepare for drawing the leaderboard
  context.clearRect(0, 0, canvas.width, canvas.height);

  // Set the background for the leaderboard
  context.fillStyle = "black";
  context.fillRect(0, 0, canvas.width, canvas.height);

  // Prepare text styling
  context.fillStyle = "white";
  context.font = "16px Arial";
  context.textAlign = "center"; // Center align the text

  // Draw the leaderboard title centered on the canvas
  context.fillText("Leaderboard:", canvas.width / 2, 20);

  // Loop through the leaderboard entries and draw them
  leaderboard.forEach((entry, index) => {
    context.fillText(
      `${index + 1}. ${entry.initials} - ${entry.score}`,
      canvas.width / 2, // Center align the leaderboard entries
      40 + 20 * index // Adjust vertical position based on index
    );
  });
}

```

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +}
Adjusted the position of the start button

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
> +}
```suggestion
// Start button functionality
function drawStartButton() {
  const buttonWidth = 100;
  const buttonHeight = 50;
  // Original positioning for the button
  const buttonX = canvas.width / 2 - buttonWidth / 2;
  const buttonY = canvas.height / 2 - buttonHeight / 2; // Middle of the canvas

  // Increase buttonY to move the button lower
  const adjustedButtonY = buttonY + 50; // Adjust this value to move the button lower as desired

  // Draw the button rectangle
  context.fillStyle = "blue";
  context.fillRect(buttonX, adjustedButtonY, buttonWidth, buttonHeight);

  // Draw the button text
  context.fillStyle = "white";
  context.font = "20px Arial";
  context.textAlign = "center";
  context.textBaseline = "middle";
  context.fillText(
    "Start Game",
    buttonX + buttonWidth / 2,
    adjustedButtonY + buttonHeight / 2
  );
}

```

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
>  });
updated the click event since we adjusted the position of the start button

2024-04-01 17:17 UTC, jboudou007 commented on BucStop/wwwroot/js/snake.js
>  });
```suggestion
canvas.addEventListener("click", function (event) {
  const rect = canvas.getBoundingClientRect();
  const x = event.clientX - rect.left;
  const y = event.clientY - rect.top;

  // Assuming these are the updated button coordinates and dimensions
  const buttonWidth = 100;
  const buttonHeight = 50;
  const buttonX = canvas.width / 2 - buttonWidth / 2;
  const adjustedButtonY = canvas.height / 2 - buttonHeight / 2 + 50; // New Y position for the button

  // Check if the click is within the button's bounds
  if (
    x > buttonX &&
    x < buttonX + buttonWidth &&
    y > adjustedButtonY &&
    y < adjustedButtonY + buttonHeight
  ) {
    gameStarted = true;
    requestAnimationFrame(gameLoop);
  }
});

```

2024-04-09 14:32 UTC, simmonsil commented
Closing since another branch was created for this

2024-04-09 14:32 UTC, closed without merging